from pylab import *
import scipy.integrate as integrate
import numpy as np
p = np.pi
x1 = arange(-2*p,4*p,p/100,dtype=float)
x = linspace(0,2*p,401)
x=x[:-1]
A=zeros((400,51))
A[:,0]=1
n = linspace(0,50,51)
for k in range(1,26):
    A[:,2*k-1]=cos(k*x)
    A[:,2*k]=sin(k*x)
c1=lstsq(A,exp(x),rcond=-1)[0]
c2=lstsq(A,cos(cos(x)),rcond=-1)[0]
def u1(x,k):
    return exp(x)*cos(k*x)
def v1(x,k):
    return exp(x)*sin(k*x)
def u2(x,k):
    return cos(cos(x))*cos(k*x)
def v2(x,k):
    return cos(cos(x))*sin(k*x)
vect1=array(zeros(51))
vect2=array(zeros(51))
for i in range(0,26):
    if i==0:
        vect1[0]=(1/(2*p))*(integrate.quad(u1,0,2*p,args=(i))[0])
        vect2[0]=(1/(2*p))*(integrate.quad(u2,0,2*p,args=(i))[0])
    else:
        vect1[2*i-1]=(1/p)*(integrate.quad(u1,0,2*p,args=(i))[0])
        vect2[2*i-1]=(1/p)*(integrate.quad(u2,0,2*p,args=(i))[0])
        vect1[2*i]=(1/p)*(integrate.quad(v1,0,2*p,args=(i))[0])
        vect2[2*i]=(1/p)*(integrate.quad(v2,0,2*p,args=(i))[0])
matmul1=matmul(A,c1)
matmul2=matmul(A,c2)
# print('Abs Difference in exp(x)     :',abs(c1-vect1))
# print('Abs Difference in cos(cos(x)):',abs(c2-vect2))
figure(1)
title('Semilog Plot Of exp(x) And Its Estimated Function')
semilogy(x1,exp(x1),color='r',label='exp(x)')
semilogy(x,matmul1,color='g',label='f(x)')
legend(loc='upper left')
xlabel('x \u2192',size=10)
ylabel('exp(x) \u2192',size=10)
grid(True)
figure(2)
title('Plot Of cos(cos(x)) And Its Estimated Function')
plot(x1,cos(cos(x1)),color='r',label='cos(cos(x))')
plot(x,matmul2,color='g',label='f(x)')
xlabel('x \u2192',size=10)
ylabel('cos(cos(x)) \u2192',size=10)
legend(loc='upper right')
grid(True)
figure(3)
title('Semilog Plot Of Theoretical and Estimated Coefficients For exp(x)')
semilogy(n,vect1,'ro',markersize=3,label='Fourier Coeff')
semilogy(n,c1,'go',markersize=3,label='Estimated Coeff')
xlabel('k \u2192',size=10)
ylabel('Coefficient Value \u2192',size=10)
legend(loc='upper right')
grid(True)
figure(4)
title('Loglog Plot Of Theoretical and Estimated Coefficients For exp(x)')
loglog(n,vect1,'ro',markersize=3,label='Fourier Coeff')
loglog(n,c1,'go',markersize=3,label='Estimated Coeff')
xlabel('k \u2192',size=10)
ylabel('Coefficient Value \u2192',size=10)
legend(loc='upper right')
grid(True)
figure(5)
title('Semilog Plot Of Theoretical and Estimated Coefficients For cos(cos(x))')
semilogy(n,vect2,'ro',markersize=3,label='Fourier Coeff')
semilogy(n,c2,'go',markersize=3,label='Estimated Coeff')
xlabel('k \u2192',size=10)
ylabel('Coefficient Value \u2192',size=10)
legend(loc='upper right')
grid(True)
figure(6)
title('Loglog Plot Of Theoretical and Estimated Coefficients For cos(cos(x))')
loglog(n,vect2,'ro',markersize=3,label='Fourier Coeff')
loglog(n,c2,'go',markersize=3,label='Estimated Coeff')
xlabel('k \u2192',size=10)
ylabel('Coefficient Value \u2192',size=10)
legend(loc='upper right')
grid(True)
figure(7)
title('Deviation Of Estimated from Theoretical Coefficients')
plot(n,abs(c1-vect1),color='red',marker='o',linestyle='',markersize=3,label='dev(exp(x))')
plot(n,abs(c2-vect2),color='blue',marker='o',linestyle='',markersize=3,label='dev(cos(cos(x)))')
xlabel('k \u2192',size=10)
ylabel('Deviation in Coefficients \u2192',size=10)
legend(loc='center right')
grid(True)
show()
